import json
import os
import sys
from pathlib import Path

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload


# ---------------------------------------------------------
# ViralSpawnTV YouTube Uploader
# ---------------------------------------------------------

YOUTUBE_SCOPES = [
    "https://www.googleapis.com/auth/youtube.upload"
]

VIDEO_PATH = Path("work/production/ViralSpawnTV_Short_V4.mp4")
METADATA_PATH = Path("work/production/ViralSpawnTV_V4_metadata.json")

# SAFETY LOCK:
# Keep all automated uploads PRIVATE while testing.
PRIVACY_STATUS = "private"


def load_credentials():
    """
    Load the OAuth token stored in the GitHub secret
    YOUTUBE_TOKEN_JSON.
    """

    token_json = os.environ.get("YOUTUBE_TOKEN_JSON")

    if not token_json:
        raise RuntimeError(
            "YOUTUBE_TOKEN_JSON GitHub secret is missing."
        )

    try:
        token_data = json.loads(token_json)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            "YOUTUBE_TOKEN_JSON is not valid JSON."
        ) from exc

    credentials = Credentials.from_authorized_user_info(
        token_data,
        scopes=YOUTUBE_SCOPES,
    )

    if credentials.expired and credentials.refresh_token:
        print("Refreshing YouTube access token...")
        credentials.refresh(Request())

    if not credentials.valid:
        raise RuntimeError(
            "YouTube credentials are not valid."
        )

    return credentials


def load_metadata():
    """
    Read title/description generated by the V4 production system.
    Falls back to safe defaults if necessary.
    """

    default_metadata = {
        "title": "Viral Streaming Moment #Shorts",
        "description": (
            "Streaming moments with original commentary and editing.\n\n"
            "#Shorts #Streaming #ViralSpawnTV"
        ),
    }

    if not METADATA_PATH.exists():
        print(
            f"WARNING: {METADATA_PATH} not found. "
            "Using fallback metadata."
        )
        return default_metadata

    try:
        with open(METADATA_PATH, "r", encoding="utf-8") as file:
            data = json.load(file)
    except Exception as exc:
        print(
            f"WARNING: Could not read metadata: {exc}"
        )
        return default_metadata

    title = str(
        data.get("title")
        or default_metadata["title"]
    ).strip()

    description = str(
        data.get("description")
        or default_metadata["description"]
    ).strip()

    # YouTube title limit.
    title = title[:100]

    # YouTube description limit.
    description = description[:5000]

    return {
        "title": title,
        "description": description,
    }


def upload_video(youtube, metadata):
    if not VIDEO_PATH.exists():
        raise FileNotFoundError(
            f"Finished V4 video was not found at: {VIDEO_PATH}"
        )

    print()
    print("---------------------------------------")
    print("ViralSpawnTV YouTube Upload")
    print("---------------------------------------")
    print(f"Video:       {VIDEO_PATH}")
    print(f"Title:       {metadata['title']}")
    print(f"Privacy:     {PRIVACY_STATUS.upper()}")
    print("---------------------------------------")
    print()

    body = {
        "snippet": {
            "title": metadata["title"],
            "description": metadata["description"],
            "categoryId": "20",
        },
        "status": {
            "privacyStatus": PRIVACY_STATUS,
            "selfDeclaredMadeForKids": False,
        },
    }

    media = MediaFileUpload(
        str(VIDEO_PATH),
        mimetype="video/mp4",
        chunksize=-1,
        resumable=True,
    )

    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media,
    )

    print("Uploading finished V4 Short to YouTube...")

    response = None

    while response is None:
        status, response = request.next_chunk()

        if status:
            percentage = int(status.progress() * 100)
            print(f"Upload progress: {percentage}%")

    return response


def main():
    print()
    print("=======================================")
    print("ViralSpawnTV YouTube Automation")
    print("=======================================")

    # Extra safety switch.
    if PRIVACY_STATUS != "private":
        raise RuntimeError(
            "SAFETY STOP: YouTube uploads must remain PRIVATE "
            "during testing."
        )

    credentials = load_credentials()

    youtube = build(
        "youtube",
        "v3",
        credentials=credentials,
        cache_discovery=False,
    )

    metadata = load_metadata()

    response = upload_video(
        youtube,
        metadata,
    )

    video_id = response.get("id")

    if not video_id:
        raise RuntimeError(
            "YouTube returned no video ID after upload."
        )

    print()
    print("=======================================")
    print("UPLOAD SUCCESSFUL")
    print("=======================================")
    print(f"YouTube Video ID: {video_id}")
    print("Privacy: PRIVATE")
    print()
    print(
        "The video should now appear in "
        "YouTube Studio → Content."
    )

    # Save upload information with the artifact.
    result_path = Path(
        "work/production/youtube_upload_result.json"
    )

    result = {
        "success": True,
        "video_id": video_id,
        "privacy_status": PRIVACY_STATUS,
        "title": metadata["title"],
    }

    with open(
        result_path,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            result,
            file,
            indent=2,
            ensure_ascii=False,
        )

    print(f"Saved upload result: {result_path}")


if __name__ == "__main__":
    try:
        main()

    except Exception as exc:
        print()
        print("=======================================")
        print("YOUTUBE UPLOAD FAILED")
        print("=======================================")
        print(str(exc))
        print()

        sys.exit(1)
